#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: emacsIntro
#+date: 2024-09-12
#+author: Lenin G. Falconí
#+email: lenin.falconi@epn.edu.ec
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.7.5)
#+cite_export:

* Encabezado
Párrafo 1. Cada párrafo se separa por medio de una línea.

Párrafo 2. Se pueden aplicar distintos estilos al texto. Por ejemplo,
*negrita* o a su vez /itálica/. También por ejemplo para escribir
código de programación puede usar ~import tensorflow as tf~. Otras
opciones que se tiene es _subrayado_ y +strike through+.

** Encabezado de Segundo nivel
Luego de escribir un encabezado ̣~C-RET~ o ~M-RET~ pueden generar otro
encabezado del mismo nivel.

* Listas
Se pueden generar dos tipos de listas: ordenadas y sin orden. Use
~M-RET~ para generar los siguientes elementos de la lista

- item a
- item b
- item c

Para una lista ordenada:

1. Item 1
2. Item 2

** Listas anidadas
Se pueden concatenar las listas usando ~RET~. Con ~M-RET~ se puede
generar los demás elementos de la lista. Para cambiar de nivel puede
usar ~M-<left>~ o ~M-<right>~. Puede usar ~S-<left>~ o ~S-<right>~ en un ítem de la lista para cambiar
el tipo de viñeta o el formato de la numeración.
1. Item 1
   - item a
   - item b
   - item c
2. Item 2
   + item a
   + item b
   + item c
3. Item 3




   
     
