#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+title: Lógica Digital
#+date: 2026-06-01
#+author: Jami Tonato Mateo Israel
#+email: mateo.jami@epn.edu.ec
#+language: Español
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.7.5)
#+cite_export: biblatex

#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_footnote_command: \footnote{%s%s}
#+latex_engraved_theme:
#+latex_compiler: pdflatex

#+latex_header: \usepackage{fancyhdr}
#+latex_header: \usepackage[top=25mm, left=25mm, right=25mm]{geometry}
#+latex_header: \usepackage{longtable}
#+latex_header: \fancyhead[R]{}
#+latex_header: \setlength\headheight{43.0pt} 

#+bibliography: bibliography.bib
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[backend=biber,style=ieee]{biblatex}


#+begin_export latex
\fancyhead[C]{\includegraphics[scale=0.05]{.././images/logoEPN.jpg}\\
ESCUELA POLITÉCNICA NACIONAL\\FACULTAD DE INGENIERÍA DE SISTEMAS\\
ARQUITECTURA DE COMPUTADORES}
\thispagestyle{fancy}
#+end_export

* Objetivos:
1. Escribir en Emacs ORG (este documento)

* Instrucciones:

- Esta tarea se desarrolla en clase.
- Utilice este documento para completarla.
- Personalice el documento con sus datos.
- Revise los vídeos expuestos en clase:
  - [[https://www.tiktok.com/@candeliousfang/video/7481760034465041686?is_from_webapp=1&sender_device=pc&web_id=7619429614976304647][video1-chatgpt-pensamiento-critico]]
  - [[https://www.tiktok.com/@dannyelcomunista/video/7497360238153190662?is_from_webapp=1&sender_device=pc&web_id=7619429614976304647][¿Qué dijo Hinton sobre democratizar la IA?]]
- Redacte una opinión, de preferencia informada, en la que discuta las
  ideas presentadas en ambos vídeos. Use la mejor puntuación y
  ortografía posibles.
- Una vea terminado suba el archivo ~.org~.
- Opcionalmente exporte a ~PDF~ y suba el ~.pdf~
* Invalidaciones de la nota
- **No se admite texto elaborado con IA**. Son sus opiniones.
- **No se admite texto mejorado con IA**. Redacte lo mejor que pueda
  cuidando la ortografía y la puntuación. Recuerde que dispone de
  ~ispell~ para revisar la ortografía.
- **No se admite texto pegado**
* Uso de Ispell y Comandos Emacs
- Para cambiar el diccionario a español ~M-x
  ispell-change-dictionary RET~ y luego escribe castellano y de
  nuevo ~RET~.
- Para optimizar la revisión de parte del documento (buffer),
  seleccione el área interés con ~C-SPC~ para iniciar el marcado y
  use las combinaciones de teclas convenientes para seleccionar los
  párrafos y oraciones a revisar. ~M-f~, ~C-e~, ~C-n~. Luego ejecute
  el comando ~M-x ispell-region~.
- Recuerde que puede cancelar todo comando con ~C-g~.
- Recuerde que ~C-z~ minimiza la pantalla. No lo use.
- Si desea deshacer use ~C-x u~
* De la Calificación
Este trabajo no evalúa ni sus opiniones ni los argumentos propuestos
por su persona. La idea es iniciar en la escritura de documentos .ORG
usando Emacs. Redacte en sus propias palabras.
Escriba sus argumentos lo mejor que pueda, guarde el documento .ORG y
Suba el documento .ORG
* Análisis Crítico
** De Chat-GPT, sus sesgos, nuestros sesgos y el Pensamiento Crítico:
Mi opinión sobre el vídeo es a favor de lo que menciona la autora, ya
que, muchas veces solemos usar la inteligencia artificial
para generar respuestas rápidas y, en muchas ocasiones, solemos creer
que todas las respuestas que la IA nos arroja es la verdad absoluta y
caemos en falacias y/o sesgos sin siquiera cuestionar fuentes o si lo
que leemos es del todo cierto. Es verdad también que si no se le
da un buen prompt a la IA, las respuestas que vamos a obtener, serán
igual de mal elaboradas o "tontas" (como lo menciona la autora) ya que
los modelos de IA, no están diseñados para crear ideas nuevas o tener
la capacidad de imaginar o debatir sobre algún tema en general, pues
estas son habilidades netamente ligadas a la capacidad humana del
pensamiento y mas en específico, del pensamiento crítico, el cuál es
descrito de forma no tan técnica como "la capacidad para pensar fuera
de la caja", de no quedarse con lo primero que se lee o se sabe, sino
mas bien, de siempre indagar profundamente en cualquier tema del cual
se busque tener un conocimiento pleno y, al usar la IA para solo
quedarse con lo primero que arroja, sin ir mas allá, se disminuye aun
más la capacidad de pensamiento critico. Es por ello, que también
comparto la posición de la autora de que, si se van a usar
herramientas de IA, se lo haga de manera coherente y siempre aplicando
la habilidad de pensamiento crítico para mejorar la capacidad de
pensar mas allá y de forma mas compleja.
** G. Hinton sobre la IA y los Sistemas Económicos ¿Es la IA democratizable?
Esta pregunta es algo complicada y depende de muchos factores para
determinar una respuesta afirmativa o negativa. Primero que todo,
tengo claro que el sistema económico actual, por el cuál nos regimos
en la mayoría del mundo, es aparentemente "sustentable" a largo plazo,
pero la realidad es que, no es así, este modelo, basado en la
acumulación, la explotación de recursos (tanto humanos, naturales y
tecnológicos) y la separación en clases, no es sustentable e incluso
teóricamente esta destinado a fracasar. Bajo este contexto y sabiendo
también la situación política y económica actual, el hecho de que una
herramienta tan "poderosa" como la IA sea "democratizable" (es decir,
que sea del pueblo y en pro del mismo) si es necesario hacer la
transición hacia el socialismo (idea que propone G. Hinton) ya que
bajo este modelo económico, se priorizaría la equidad y el control de
recursos de manera colectiva y no de forma privada. Por lo tanto, yo,
estoy de acuerdo con la posición del "padre de la IA" de que la única
solución real, para alcanzar un futuro utópico con las herramientas
tecnológicas, en especial la IA, es bajo el modelo económico del
socialismo, en el cuál la IA si sería democratizable y accesible en
pro de todos.



