#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_footnote_command: \footnote{%s%s}
#+latex_engraved_theme:
#+latex_compiler: pdflatex
#+date: \today

#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: S8-Buses-del-Sistema-Resumen
#+date: <2024-06-24 Mon>
#+author: Lenin G. Falconí
#+email: lenin.falconi@epn.edu.ec
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.7.5)
#+cite_export:

* ¿Qué se denomina estructura de interconexión?

- Las estructuras de interconexión son el conjunto de líneas que conectan diversos módulos.
- Cada estructura depende del tipo intercambio de información requerida.

* ¿Cuáles son los módulos disponibles en un computador?
1. Memoria
2. Procesador
3. Módulo de E/S

* ¿Qué tipo de transferencias deben dar cobertura las estructuras de interconexión?

1. Memoria $\leftrightarrow$ procesador
2. E/S $\leftrightarrow$ procesador
3. Memoria $\leftrightarrow$ E/S: Direct Memory Access (DMA)

* ¿Qué es el DMA?

Cuando el módulo de E/S intercambia datos directamente con la memoria sin que intervenga el CPU

* ¿Qué es un Bus?

- Es un camino de comunicación entre dos o más
dispositivos
- Es un medio de transmisión compartido.
- Para evitar colisiones en la transmisión de datos es necesario que un sólo
dispositivo transmita en un momento dado.


* ¿Qué es una comunicación serial?

Es aquella en la que se transmite una secuencia de dígitos binarios a
través del bus de datos

* ¿Qué es una comunicación paralelo?  Es aquella en la que se usan
varias líneas del bus para transmitir dígitos binarios de manera simultánea.

* ¿A qué se denomina el ancho del bus?

Al número de líneas del bus o el número de bits que se transmiten
simultáneamente.

* ¿Qué son las líneas de datos?

Son las que proporcionan un camino para transmitir datos entre los
módulos del sistema

* ¿Que són las líneas de dirección?

Son las que especifican la
dirección de la fuente o destino del dato situado en el bus de datos

* Si el al ancho del bus de direcciones es $N$, ¿cuál es la capacidad
máxima de memoria?

Se entendería que la capacidad máxima sería $2^N$

* ¿Para qué sirven las líneas de control?

Dirigen o coordinan el acceso y uso de las líneas de datos y de
direcciones.

* ¿Qué significa que un bus de datos sea dedicado?

El bus tiene prestaciones especificas y puede dividirse en bus de
direcciones y en bus de datos.

* ¿Qué significaque un bus de datos es multiplexado?

Significa que el bus está diseñado para funcionar tanto como bus de
direcciones como de datos y en consecuencia optimizar el uso de las
líneas eléctricas.


* ¿En qué consiste el método de arbitraje centralizado?

Se dispone de un controlador del bus o árbitro que asigna el tiempo de
acceso al bus. Es un controlador central. Como consecuencia de la
acción, se asigna a un módulo, el procesador o dispositivo como
/maestro/ del bus.

* ¿En qué consiste el método de arbitraje distribuido?

Cada módulo dispone de lógica para controlar el acceso y los módulos
actúan para compartir elbus.

* ¿Cuál fue la razón principal para cambiar del sistema de bus
compartido al sistema de punto a punto?

- Limitaciones eléctricas al incrementar la frecuencia del bus ya que se
incrementa la dificultad de realizar la sincronización y el arbitraje
a una frecuencia mayor con mayores tasas de datos.

- La disponibilidad de varios procesadores y mayor memoria en un mismo
chip amplifica la dificultad de incrementar la velocidad del bus y
reducir la latencia a la par del rendimiento del procesador.



